#----------------------------------------------------------------------
# Makefile for CS415/515 Assignment 1
# Written by Prof. Jingke Li (lij@pdx.edu) for this class
# NOT written by Brooke Czerwinski. 
#----------------------------------------------------------------------

.PRECIOUS: %.cpp %.java

.cpp:   $*.cpp
	g++ -pthread -g queue.cpp $*.cpp -o $*

ProdCons1: ProdCons1.java
	javac -g ProdCons1.java

ProdCons2: ProdCons2.java
	javac -g ProdCons2.java

ProdCons3: ProdCons3.java
	javac -g ProdCons3.java

