#----------------------------------------------------------------------
# CS415/515 Generic
# Written by Prof. Jingke Li (lij@pdx.edu) for this class
# NOT written by Brooke Czerwinski. 
#----------------------------------------------------------------------

%: %.c
	gcc -g -o $@ $< 

%: %.cpp
	g++ -g -o $@ $< 

%: %.f90
	gfortran -g -o $@ $< 

%: %.chpl
	chpl -g -o $@ $< 

