#----------------------------------------------------------------------
# Makefile for CS415/515 Assignment 2
# Written by Prof. Jingke Li (lij@pdx.edu) for this class
# NOT written by Brooke Czerwinski. 
#----------------------------------------------------------------------

.PRECIOUS: %.cpp

.cpp:   $*.cpp
	g++ -g -fopenmp -o $@ $<

